site_name: "Docs | Plasma Engine"
theme: flatly
docs_dir: "src/"

repo_url: "https://github.com/PlasmaEngine/PlasmaDocs"
repo_name: GitHub
site_description: "The documentation site of the Plasma Game Engine."
copyright: "Copyright &copy; 2021 Plasma Engine. Released under the MIT License."

nav:
  - Home: index.md
  - "Getting Started" : "/getting_started/"
  - Manual:
    - Manual: manual/index.markdown
    - AI: manual/plasmamanual/ai.markdown
    - Architecture: 
      - manual/plasmamanual/architecture/architecture.markdown
      - Archtypes: manual/plasmamanual/architecture/archetypes/archtype_basics.markdown
      - Cogs: 
        - manual/plasmamanual/architecture/cogs/cogs.markdown
        - Game Objects: manual/plasmamanual/architecture/cogs/gameobjectsconcept.markdown
        - Object Store: manual/plasmamanual/architecture/cogs/objectstore.markdown
      - Objects: 
        - manual/plasmamanual/architecture/objects/objects.markdown
        - manual/plasmamanual/architecture/objects/gamesession.markdown 
        - manual/plasmamanual/architecture/objects/spaces.markdown
        - manual/plasmamanual/architecture/objects/levelsettings.markdown
      - Resources:
        - Resources: manual/plasmamanual/architecture/resources/resource.markdown
        - Levels: manual/plasmamanual/architecture/resources/level.markdown
        - Fonts: manual/plasmamanual/architecture/fonts/fonts.markdown
        - "Resource Table": manual/plasmamanual/architecture/resources/resourcestable.markdown

    - Audio: manual/plasmamanual/audio.markdown
    - Editor: 
      - Editor: manual/plasmamanual/editor/index.markdown
      - Tags: manual/plasmamanual/editor/tags.markdown

  - Contributing: 
    - "Getting Started": source_docs/getting_started.md
    - "Plasma Code": source_docs/plasma_code.markdown
    - "Plasma Overview": source_docs/plasma_overview.markdown
    - Components: source_docs/components.md
    - "Custom Event Names": source_docs/custom_event_names.markdown
    - Editor: source_docs/editor.markdown
    - Engine: source_docs/engine.markdown
    - Enums: source_docs/enums.markdown
    - "Meta Binding": source_docs/meta_bindings.markdown
    - "Adding Platforms": source_docs/platform.markdown
    - Widgets: source_docs/widgets.markdown