site_name: PlasmaDocs
site_url: https://plasmaengine.github.io/PlasmaDocs/
site_author: PlasmaDev
site_description: Documentation on the Plasma Game Engine

theme: windmill-dark
extra.logo: https://raw.githubusercontent.com/PlasmaEngine/PlasmaDocs/master/assets/PlasmaLogo.png
extra.version: 0.0.1

plugins:
    - search:
        separator: '[\s\-\.]+'