site_name: PlasmaDocs
site_url: https://plasmaengine.github.io/PlasmaDocs/
site_author: PlasmaDev
site_description: Documentation on the Plasma Game Engine

plugins:
    - search:
        separator: '[\s\-\.]+'