site_name: PlasmaDocs
site_url: https://plasmaengine.github.io/PlasmaDocs/
site_author: PlasmaDev
site_description: Documentation on the Plasma Game Engine

theme:
    name: readthedocs
    custom_dir: mkdocs-windmill-dark

plugins:
    - search:
        separator: '[\s\-\.]+'